# Brand Names for Image Retrieval From Instagram

**Goal:** process data to get all brand names to search for images on instagram

### 1. Import dependencies

Install non-standard libraries: requests, BeautifulSoup

In [66]:
import os
import pandas as pd
import numpy as np

### 2. Get Brand Names from Data

In [67]:
# to specify
directory= r'C:\Users\r_the\Documents\DLfM_BrandManagement\other_project\brand_hashtag_and_account'
os.chdir(directory)

#### 2.1 Load all dataframes 

There are dataframes for apparel and beverage brand category. Then, there are total dataframes that include both brand categories and add the information about the full name and instagram name of the brand name. 

First, we get out apparel brand dataframes.

In [81]:
#convert to dataframe 

data1 = pd.read_csv('apparel_brands.txt', header=None)
data1.columns = ["apparel_brands"]
data1 = data1.sort_values(by='apparel_brands')
print(data1.head())
print(data1.info())

    apparel_brands
10     abercrombie
12          adidas
6        anntaylor
0   bananarepublic
14        carhartt
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 10 to 13
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   apparel_brands  29 non-null     object
dtypes: object(1)
memory usage: 464.0+ bytes
None

In [80]:
data2 = pd.read_csv('apparel_full_brand_names.txt', header=None)
data2.columns = ["apparel_full_brand_names"]
data2 = data2.sort_values(by='apparel_full_brand_names')
print(data2.head())
print(data2.info())

  apparel_full_brand_names
0      Abercrombie & Fitch
1                   Adidas
2               Ann Taylor
3          Banana Republic
4                 Carhartt
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 0 to 28
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   apparel_full_brand_names  29 non-null     object
dtypes: object(1)
memory usage: 464.0+ bytes
None

In [79]:
data3 = pd.read_csv('official_apparel_brands.txt', header=None)
data3.columns = ["official_apparel_brands"]
data3 = data3.sort_values(by='official_apparel_brands')
print(data3.head())
print(data3.info())

   official_apparel_brands
10             abercrombie
12                  adidas
6                anntaylor
0           bananarepublic
14                carhartt
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 10 to 13
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   official_apparel_brands  29 non-null     object
dtypes: object(1)
memory usage: 464.0+ bytes
None

Get out all beverage brands.

In [78]:
data4 = pd.read_csv('beverage_brands.txt', header=None)
data4.columns = ["beverage_brands"]
data4 = data4.sort_values(by='beverage_brands',ignore_index=True)
print(data4.head())
print(data4.info())

  beverage_brands
0         bacardi
1         bigelow
2        budlight
3       budweiser
4        cocacola
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   beverage_brands  27 non-null     object
dtypes: object(1)
memory usage: 344.0+ bytes
None

In [77]:
data5 = pd.read_csv('beverage_full_brand_names.txt', header=None)
data5.columns = ["beverage_full_brand_names"]
data5 = data5.sort_values(by='beverage_full_brand_names',ignore_index=True)
print(data5.head())
print(data5.info())

  beverage_full_brand_names
0                   Bacardi
1             Bigelow's Tea
2                 Bud Light
3                 Budweiser
4                 Coca-Cola
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   beverage_full_brand_names  27 non-null     object
dtypes: object(1)
memory usage: 344.0+ bytes
None

In [76]:
data6 = pd.read_csv('official_beverage_brands.txt', header=None)
data6.columns = ["official_beverage_brands"]
data6 = data6.sort_values(by='official_beverage_brands',ignore_index=True)
print(data6.head())
print(data6.info())

  official_beverage_brands
0               bacardiusa
1               bigelowtea
2                 budlight
3                budweiser
4                 cocacola
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   official_beverage_brands  24 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes
None

Get apparel + beverage dataframes 

Convert the brand names of a user profile to a full brand name or a hashtag to a full brandname or vice versa.

In [60]:
data7 = pd.read_csv('official_account_to_brand_name.txt')
data7.sort_values(by='firm_account')
data7.columns = ['firm_account', 'brand_full_name']
print(data7)
print(data7.info())

              firm_account       brand_full_name
0              abercrombie   Abercrombie & Fitch
1                   adidas                Adidas
2                anntaylor            Ann Taylor
3               bacardiusa               Bacardi
4           bananarepublic       Banana Republic
5               bigelowtea         Bigelow`s Tea
6                 budlight             Bud Light
7                budweiser             Budweiser
8                 carhartt              Carhartt
9                 cocacola             Coca-Cola
10                converse              Converse
11              coorslight           Coors Light
12                  corona                Corona
13           dockerskhakis               Dockers
14            dolcegabbana       Dolce & Gabbana
15             domperignon          Dom Perignon
16                drpepper             Dr Pepper
17              eddiebauer           Eddie Bauer
18                   fanta                 Fanta
19                     gap                   Gap
20                gatorade              Gatorade
21               greygoose            Grey Goose
22                   gucci                 Gucci
23                   guess                 Guess
24             hanesbrasil                 Hanes
25             hollisterco             Hollister
26               honesttea            Honest Tea
27          jackdaniels_us         Jack Daniel`s
28                   jcrew               J. Crew
29           joeboxerlicky             Joe Boxer
30            juicycouture         Juicy Couture
31             kennethcole          Kenneth Cole
32             korbel_1882                Korbel
33                   levis                Levi`s
34                  lipton                Lipton
35                  llbean             L.L. Bean
36            luckybrandme     Lucky Brand Jeans
37             moetchandon        Moet & Chandon
38           monsterenergy       Monster (drink)
39              nesquikusa               NesQuik
40                 oldnavy              Old Navy
41             oshkoshkids               OshKosh
42                   prada                 Prada
43             ralphlauren          Ralph Lauren
44  sanpellegrino_official        San Pellegrino
45                 snapple               Snapple
46                    tazo                  Tazo
47           tommyhilfiger        Tommy Hilfiger
48             underarmour          Under Armour
49         urbanoutfitters      Urban Outfitters
50         victoriassecret     Victoria`s Secret
51            vitaminwater          vitaminwater
52                  welchs               Welch`s
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   firm_account     53 non-null     object
 1   brand_full_name  53 non-null     object
dtypes: object(2)
memory usage: 976.0+ bytes
None

In [59]:
data8 = pd.read_csv('instagram_hashtag_to_brand_name.txt')
data8.columns = ['instagram_hashtag', 'brand_full_name']
print(data8)
print(data8.info())

   instagram_hashtag       brand_full_name
0              fanta                 Fanta
1         coorslight           Coors Light
2          greygoose            Grey Goose
3             corona                Corona
4      monsterenergy       Monster (drink)
5         minutemaid           Minute Maid
6           gatorade              Gatorade
7        jackdaniels         Jack Daniel`s
8        abercrombie   Abercrombie & Fitch
9           carhartt              Carhartt
10        eddiebauer           Eddie Bauer
11          joeboxer             Joe Boxer
12       underarmour          Under Armour
13            adidas                Adidas
14          cocacola             Coca-Cola
15      juicycouture         Juicy Couture
16   urbanoutfitters      Urban Outfitters
17         anntaylor            Ann Taylor
18          converse              Converse
19               gap                   Gap
20       kennethcole          Kenneth Cole
21           oldnavy              Old Navy
22   victoriassecret     Victoria`s Secret
23            korbel                Korbel
24      vitaminwater          vitaminwater
25           bacardi               Bacardi
26             levis                Levi`s
27             prada                 Prada
28    bananarepublic       Banana Republic
29           dockers               Dockers
30             guess                 Guess
31            lipton                Lipton
32     sanpellegrino        San Pellegrino
33           bigelow         Bigelow`s Tea
34      dolcegabbana       Dolce & Gabbana
35             hanes                 Hanes
36        luckybrand     Lucky Brand Jeans
37           snapple               Snapple
38          budlight             Bud Light
39       domperignon          Dom Perignon
40         honesttea            Honest Tea
41         budweiser             Budweiser
42          drpepper             Dr Pepper
43       moetchandon        Moet & Chandon
44              tazo                  Tazo
45            llbean             L.L. Bean
46           oshkosh               OshKosh
47       ralphlauren          Ralph Lauren
48             gucci                 Gucci
49     tommyhilfiger        Tommy Hilfiger
50         hollister             Hollister
51             jcrew               J. Crew
52            welchs               Welch`s
53             motts                Mott`s
54           nesquik               NesQuik
55         swissmiss            Swiss Miss
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   instagram_hashtag  56 non-null     object
 1   brand_full_name    56 non-null     object
dtypes: object(2)
memory usage: 1.0+ KB
None

#### 2.2 Build global dataframe from single dataframes

From the individual dataframes about apparel and beverage, a global dataframe is built which gives an overview over all brand names and categorizes them into a brand category.

In [30]:
# data cleaning apparel
data2['apparel_full_brand_names'].replace(" Levi's", "Levi's", inplace=True) #levi's aposthrophe different to same 
data7['brand_full_name'].replace(" Levi`s", "Levi's", inplace=True) #levi's aposthrophe different to same
data8['brand_full_name'].replace(" Levi`s", "Levi's", inplace=True) #levi's aposthrophe different to same

data2['apparel_full_brand_names'].replace(" Victoria's Secret", "Victoria's Secret", inplace=True) #victoria's secret's aposthrophe different to same 
data7['brand_full_name'].replace(" Victoria`s Secret", "Victoria's Secret", inplace=True) #victoria's secret's aposthrophe different to same 
data8['brand_full_name'].replace(" Victoria`s Secret", "Victoria's Secret", inplace=True) #victoria's secret's aposthrophe different to same

In [28]:
# data cleaning beverage
data5['beverage_full_brand_names'].replace(" Bigelow's Tea", "Bigelow's Tea", inplace=True) #bigelow's aposthrophe different to same 
data7['brand_full_name'].replace(' Bigelow`s Tea', "Bigelow's Tea", inplace=True) #bigelow's secret's aposthrophe different to same 
data8['brand_full_name'].replace(' Bigelow`s Tea', "Bigelow's Tea", inplace=True) #bigelow's secret's aposthrophe different to same 

data5['beverage_full_brand_names'].replace(" Jack Daniel's", "Jack Daniel's", inplace=True) #jack daniel's aposthrophe different to same 
data7['brand_full_name'].replace(' Jack Daniel`s', "Jack Daniel's", inplace=True) #jack daniel's aposthrophe different to same
data8['brand_full_name'].replace(' Jack Daniel`s', "Jack Daniel's", inplace=True) #jack daniel's aposthrophe different to same

data5['beverage_full_brand_names'].replace(" Mott's", "Mott's", inplace=True) #mott's aposthrophe different to same 
data7['brand_full_name'].replace(' Mott`s', "Mott's", inplace=True) #mott's aposthrophe different to same 
data8['brand_full_name'].replace(' Mott`s', "Mott's", inplace=True) #mott's aposthrophe different to same 

data5['beverage_full_brand_names'].replace(" Welch's", "Welch's", inplace=True) #welch's aposthrophe different to same 
data7['brand_full_name'].replace(' Welch`s', "Welch's", inplace=True) #welch's aposthrophe different to same 
data8['brand_full_name'].replace(' Welch`s', "Welch's", inplace=True) #welch's aposthrophe different to same

data5['beverage_full_brand_names'].replace(' Monster (drink)', "Welch's", inplace=True) #welch's aposthrophe different to same 
data7['brand_full_name'].replace(' Monster (drink)', ' Monster', inplace=True) #remove (drink) from Monster
data8['brand_full_name'].replace(' Monster (drink)', ' Monster', inplace=True) #remove (drink) from Monster

data5['beverage_full_brand_names'].replace(' vitaminwater', "Welch's", inplace=True) #welch's aposthrophe different to same 
data7['brand_full_name'].replace(' vitaminwater', ' Vitaminwater', inplace=True) #vitaminwater lowercase v to uppercase V
data8['brand_full_name'].replace(' vitaminwater', ' Vitaminwater', inplace=True) #vitaminwater lowercase v  to uppercase V

In [32]:
data13 = pd.concat([data1, data3], axis=1)
data13.head()

   apparel_brands official_apparel_brands
0  bananarepublic          bananarepublic
1    juicycouture            juicycouture
2     underarmour             underarmour
3           levis                   levis
4      eddiebauer              eddiebauer

In [62]:
data27 = pd.merge(data2, data7, how='outer', left_on='apparel_full_brand_names', right_on='brand_full_name')
data27.head()

  apparel_full_brand_names    firm_account       brand_full_name
0      Abercrombie & Fitch     abercrombie   Abercrombie & Fitch
1                   Adidas          adidas                Adidas
2               Ann Taylor       anntaylor            Ann Taylor
3          Banana Republic  bananarepublic       Banana Republic
4                 Carhartt        carhartt              Carhartt

In [63]:
data1327 = pd.merge(data13, data27, how='outer', left_on='official_apparel_brands', right_on='firm_account')
data1327 = data1327.where(pd.notnull(data1327), None)
data1327.head()

,apparel_brands,official_apparel_brands,apparel_full_brand_names,firm_account,brand_full_name
0,bananarepublic,bananarepublic,Banana Republic,bananarepublic,Banana Republic
1,juicycouture,juicycouture,Juicy Couture,juicycouture,Juicy Couture
2,underarmour,underarmour,Under Armour,underarmour,Under Armour
3,levis,levis,None,levis,Levi`s
4,eddiebauer,eddiebauer,Eddie Bauer,eddiebauer,Eddie Bauer

In [35]:
import numpy as np
def f(row):
    if row['apparel_full_brand_names'] != None:
        val = 'apparel'
    else:
        val = 'beverage'
    return val

In [36]:
data1327['brand_category']  = data1327.apply(f, axis=1)
data1327

,apparel_brands,official_apparel_brands,apparel_full_brand_names,firm_account,brand_full_name,brand_category
0,bananarepublic,bananarepublic,Banana Republic,bananarepublic,Banana Republic,apparel
1,juicycouture,juicycouture,Juicy Couture,juicycouture,Juicy Couture,apparel
2,underarmour,underarmour,Under Armour,underarmour,Under Armour,apparel
3,levis,levis,Levi's,levis,Levi's,apparel
4,eddiebauer,eddiebauer,Eddie Bauer,eddiebauer,Eddie Bauer,apparel
5,oldnavy,oldnavy,Old Navy,oldnavy,Old Navy,apparel
6,anntaylor,anntaylor,Ann Taylor,anntaylor,Ann Taylor,apparel
7,converse,converse,Converse,converse,Converse,apparel
8,dolcegabbana,dolcegabbana,Dolce & Gabbana,dolcegabbana,Dolce & Gabbana,apparel
9,prada,prada,Prada,prada,Prada,apparel
10,abercrombie,abercrombie,Abercrombie & Fitch,abercrombie,Abercrombie & Fitch,apparel
11,gap,gap,Gap,gap,Gap,apparel
12,adidas,adidas,Adidas,adidas,Adidas,apparel
13,victoriassecret,victoriassecret,Victoria's Secret,victoriassecret,Victoria's Secret,apparel
14,carhartt,carhartt,Carhartt,carhartt,Carhartt,apparel
15,luckybrand,luckybrandme,Lucky Brand Jeans,luckybrandme,Lucky Brand Jeans,apparel
16,dockers,dockerskhakis,Dockers,dockerskhakis,Dockers,apparel
17,kennethcole,kennethcole,Kenneth Cole,kennethcole,Kenneth Cole,apparel
18,guess,guess,Guess,guess,Guess,apparel
19,hanes,hanesbrasil,Hanes,hanesbrasil,Hanes,apparel
20,joeboxer,joeboxerlicky,Joe Boxer,joeboxerlicky,Joe Boxer,apparel
21,urbanoutfitters,urbanoutfitters,Urban Outfitters,urbanoutfitters,Urban Outfitters,apparel
22,llbean,llbean,L.L. Bean,llbean,L.L. Bean,apparel
23,oshkosh,oshkoshkids,OshKosh,oshkoshkids,OshKosh,apparel
24,ralphlauren,ralphlauren,Ralph Lauren,ralphlauren,Ralph Lauren,apparel
25,gucci,gucci,Gucci,gucci,Gucci,apparel
26,tommyhilfiger,tommyhilfiger,Tommy Hilfiger,tommyhilfiger,Tommy Hilfiger,apparel
27,hollister,hollisterco,Hollister,hollisterco,Hollister,apparel
28,jcrew,jcrew,J. Crew,jcrew,J. Crew,apparel
29,None,None,None,bacardiusa,Bacardi,beverage
30,None,None,None,bigelowtea,Bigelow's Tea,beverage
31,None,None,None,budlight,Bud Light,beverage
32,None,None,None,budweiser,Budweiser,beverage
33,None,None,None,cocacola,Coca-Cola,beverage
34,None,None,None,coorslight,Coors Light,beverage
35,None,None,None,corona,Corona,beverage
36,None,None,None,domperignon,Dom Perignon,beverage
37,None,None,None,drpepper,Dr Pepper,beverage
38,None,None,None,fanta,Fanta,beverage
39,None,None,None,gatorade,Gatorade,beverage
40,None,None,None,greygoose,Grey Goose,beverage
41,None,None,None,honesttea,Honest Tea,beverage
42,None,None,None,jackdaniels_us,Jack Daniel's,beverage
43,None,None,None,korbel_1882,Korbel,beverage
44,None,None,None,lipton,Lipton,beverage
45,None,None,None,moetchandon,Moet & Chandon,beverage
46,None,None,None,monsterenergy,Monster,beverage
47,None,None,None,nesquikusa,NesQuik,beverage
48,None,None,None,sanpellegrino_official,San Pellegrino,beverage
49,None,None,None,snapple,Snapple,beverage
50,None,None,None,tazo,Tazo,beverage
51,None,None,None,vitaminwater,Vitaminwater,beverage
52,None,None,None,welchs,Welch's,beverage

In [64]:
data45 = pd.concat([data4, data5], axis=1)
data45.head()

  beverage_brands beverage_full_brand_names
0         bacardi                   Bacardi
1         bigelow             Bigelow's Tea
2        budlight                 Bud Light
3       budweiser                 Budweiser
4        cocacola                 Coca-Cola

In [85]:
subdata45=data45.iloc[[16,19,23],]
data45=data45.drop([16,19,23])
data45=data45.append(subdata45)
data45 = data45.set_index([pd.Index([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26])])
data45.head()

  beverage_brands beverage_full_brand_names
0         bacardi                   Bacardi
1         bigelow             Bigelow's Tea
2        budlight                 Bud Light
3       budweiser                 Budweiser
4        cocacola                 Coca-Cola

In [42]:
data456 = pd.concat([data45, data6], axis=1)
data456.head()

   beverage_brands beverage_full_brand_names official_beverage_brands
0          bacardi                   Bacardi               bacardiusa
1          bigelow             Bigelow's Tea               bigelowtea
2         budlight                 Bud Light                 budlight
3        budweiser                 Budweiser                budweiser
4         cocacola                 Coca-Cola                 cocacola
5       coorslight               Coors Light               coorslight
6           corona                    Corona                   corona
7      domperignon              Dom Perignon              domperignon
8         drpepper                 Dr Pepper                 drpepper
9            fanta                     Fanta                    fanta
10        gatorade                  Gatorade                 gatorade
11       greygoose                Grey Goose                greygoose
12       honesttea                Honest Tea                honesttea
13     jackdaniels             Jack Daniel's           jackdaniels_us
14          korbel                    Korbel              korbel_1882
15          lipton                    Lipton                   lipton
16     moetchandon            Moet & Chandon              moetchandon
17   monsterenergy                   Monster            monsterenergy
18         nesquik                   NesQuik               nesquikusa
19   sanpellegrino            San Pellegrino   sanpellegrino_official
20         snapple                   Snapple                  snapple
21            tazo                      Tazo                     tazo
22    vitaminwater              Vitaminwater             vitaminwater
23          welchs                   Welch's                   welchs
24      minutemaid               Minute Maid                      NaN
25           motts                    Mott's                      NaN
26       swissmiss                Swiss Miss                      NaN

In [31]:
data78 = pd.merge(data7, data8, how='outer', left_on='brand_full_name', right_on='brand_full_name')
data78 = data78[['instagram_hashtag', 'firm_account','brand_full_name' ]] #reorder columns 
data78.head()

   instagram_hashtag            firm_account       brand_full_name
0        abercrombie             abercrombie   Abercrombie & Fitch
1             adidas                  adidas                Adidas
2          anntaylor               anntaylor            Ann Taylor
3            bacardi              bacardiusa               Bacardi
4     bananarepublic          bananarepublic       Banana Republic
5            bigelow              bigelowtea         Bigelow's Tea
6           budlight                budlight             Bud Light
7          budweiser               budweiser             Budweiser
8           carhartt                carhartt              Carhartt
9           cocacola                cocacola             Coca-Cola
10          converse                converse              Converse
11        coorslight              coorslight           Coors Light
12            corona                  corona                Corona
13           dockers           dockerskhakis               Dockers
14      dolcegabbana            dolcegabbana       Dolce & Gabbana
15       domperignon             domperignon          Dom Perignon
16          drpepper                drpepper             Dr Pepper
17        eddiebauer              eddiebauer           Eddie Bauer
18             fanta                   fanta                 Fanta
19               gap                     gap                   Gap
20          gatorade                gatorade              Gatorade
21         greygoose               greygoose            Grey Goose
22             gucci                   gucci                 Gucci
23             guess                   guess                 Guess
24             hanes             hanesbrasil                 Hanes
25         hollister             hollisterco             Hollister
26         honesttea               honesttea            Honest Tea
27       jackdaniels          jackdaniels_us         Jack Daniel's
28             jcrew                   jcrew               J. Crew
29          joeboxer           joeboxerlicky             Joe Boxer
30      juicycouture            juicycouture         Juicy Couture
31       kennethcole             kennethcole          Kenneth Cole
32            korbel             korbel_1882                Korbel
33             levis                   levis                Levi's
34            lipton                  lipton                Lipton
35            llbean                  llbean             L.L. Bean
36        luckybrand            luckybrandme     Lucky Brand Jeans
37       moetchandon             moetchandon        Moet & Chandon
38     monsterenergy           monsterenergy               Monster
39           nesquik              nesquikusa               NesQuik
40           oldnavy                 oldnavy              Old Navy
41           oshkosh             oshkoshkids               OshKosh
42             prada                   prada                 Prada
43       ralphlauren             ralphlauren          Ralph Lauren
44     sanpellegrino  sanpellegrino_official        San Pellegrino
45           snapple                 snapple               Snapple
46              tazo                    tazo                  Tazo
47     tommyhilfiger           tommyhilfiger        Tommy Hilfiger
48       underarmour             underarmour          Under Armour
49   urbanoutfitters         urbanoutfitters      Urban Outfitters
50   victoriassecret         victoriassecret     Victoria's Secret
51      vitaminwater            vitaminwater          Vitaminwater
52            welchs                  welchs               Welch's
53        minutemaid                     NaN           Minute Maid
54             motts                     NaN                Mott's
55         swissmiss                     NaN            Swiss Miss

In [43]:
data45678 = pd.merge(data456, data78, how='outer', left_on='beverage_full_brand_names', right_on='brand_full_name')
data45678 = data45678.where(pd.notnull(data45678), None)
data45678.head()

,beverage_brands,beverage_full_brand_names,official_beverage_brands,instagram_hashtag,firm_account,brand_full_name
0,bacardi,Bacardi,bacardiusa,bacardi,bacardiusa,Bacardi
1,bigelow,Bigelow's Tea,bigelowtea,bigelow,bigelowtea,Bigelow's Tea
2,budlight,Bud Light,budlight,budlight,budlight,Bud Light
3,budweiser,Budweiser,budweiser,budweiser,budweiser,Budweiser
4,cocacola,Coca-Cola,cocacola,cocacola,cocacola,Coca-Cola
5,coorslight,Coors Light,coorslight,coorslight,coorslight,Coors Light
6,corona,Corona,corona,corona,corona,Corona
7,domperignon,Dom Perignon,domperignon,domperignon,domperignon,Dom Perignon
8,drpepper,Dr Pepper,drpepper,drpepper,drpepper,Dr Pepper
9,fanta,Fanta,fanta,fanta,fanta,Fanta
10,gatorade,Gatorade,gatorade,gatorade,gatorade,Gatorade
11,greygoose,Grey Goose,greygoose,greygoose,greygoose,Grey Goose
12,honesttea,Honest Tea,honesttea,honesttea,honesttea,Honest Tea
13,jackdaniels,Jack Daniel's,jackdaniels_us,jackdaniels,jackdaniels_us,Jack Daniel's
14,korbel,Korbel,korbel_1882,korbel,korbel_1882,Korbel
15,lipton,Lipton,lipton,lipton,lipton,Lipton
16,moetchandon,Moet & Chandon,moetchandon,moetchandon,moetchandon,Moet & Chandon
17,monsterenergy,Monster,monsterenergy,monsterenergy,monsterenergy,Monster
18,nesquik,NesQuik,nesquikusa,nesquik,nesquikusa,NesQuik
19,sanpellegrino,San Pellegrino,sanpellegrino_official,sanpellegrino,sanpellegrino_official,San Pellegrino
20,snapple,Snapple,snapple,snapple,snapple,Snapple
21,tazo,Tazo,tazo,tazo,tazo,Tazo
22,vitaminwater,Vitaminwater,vitaminwater,vitaminwater,vitaminwater,Vitaminwater
23,welchs,Welch's,welchs,welchs,welchs,Welch's
24,minutemaid,Minute Maid,None,minutemaid,None,Minute Maid
25,motts,Mott's,None,motts,None,Mott's
26,swissmiss,Swiss Miss,None,swissmiss,None,Swiss Miss
27,None,None,None,abercrombie,abercrombie,Abercrombie & Fitch
28,None,None,None,adidas,adidas,Adidas
29,None,None,None,anntaylor,anntaylor,Ann Taylor
30,None,None,None,bananarepublic,bananarepublic,Banana Republic
31,None,None,None,carhartt,carhartt,Carhartt
32,None,None,None,converse,converse,Converse
33,None,None,None,dockers,dockerskhakis,Dockers
34,None,None,None,dolcegabbana,dolcegabbana,Dolce & Gabbana
35,None,None,None,eddiebauer,eddiebauer,Eddie Bauer
36,None,None,None,gap,gap,Gap
37,None,None,None,gucci,gucci,Gucci
38,None,None,None,guess,guess,Guess
39,None,None,None,hanes,hanesbrasil,Hanes
40,None,None,None,hollister,hollisterco,Hollister
41,None,None,None,jcrew,jcrew,J. Crew
42,None,None,None,joeboxer,joeboxerlicky,Joe Boxer
43,None,None,None,juicycouture,juicycouture,Juicy Couture
44,None,None,None,kennethcole,kennethcole,Kenneth Cole
45,None,None,None,levis,levis,Levi's
46,None,None,None,llbean,llbean,L.L. Bean
47,None,None,None,luckybrand,luckybrandme,Lucky Brand Jeans
48,None,None,None,oldnavy,oldnavy,Old Navy
49,None,None,None,oshkosh,oshkoshkids,OshKosh
50,None,None,None,prada,prada,Prada
51,None,None,None,ralphlauren,ralphlauren,Ralph Lauren
52,None,None,None,tommyhilfiger,tommyhilfiger,Tommy Hilfiger
53,None,None,None,underarmour,underarmour,Under Armour
54,None,None,None,urbanoutfitters,urbanoutfitters,Urban Outfitters
55,None,None,None,victoriassecret,victoriassecret,Victoria's Secret

In [44]:
import numpy as np
def f(row):
    if row['beverage_full_brand_names'] == None:
        val = 'apparel'
    else:
        val = 'beverage'
    return val

In [45]:
data45678['brand_category']  = data45678.apply(f, axis=1)
data45678

,beverage_brands,beverage_full_brand_names,official_beverage_brands,instagram_hashtag,firm_account,brand_full_name,brand_category
0,bacardi,Bacardi,bacardiusa,bacardi,bacardiusa,Bacardi,beverage
1,bigelow,Bigelow's Tea,bigelowtea,bigelow,bigelowtea,Bigelow's Tea,beverage
2,budlight,Bud Light,budlight,budlight,budlight,Bud Light,beverage
3,budweiser,Budweiser,budweiser,budweiser,budweiser,Budweiser,beverage
4,cocacola,Coca-Cola,cocacola,cocacola,cocacola,Coca-Cola,beverage
5,coorslight,Coors Light,coorslight,coorslight,coorslight,Coors Light,beverage
6,corona,Corona,corona,corona,corona,Corona,beverage
7,domperignon,Dom Perignon,domperignon,domperignon,domperignon,Dom Perignon,beverage
8,drpepper,Dr Pepper,drpepper,drpepper,drpepper,Dr Pepper,beverage
9,fanta,Fanta,fanta,fanta,fanta,Fanta,beverage
10,gatorade,Gatorade,gatorade,gatorade,gatorade,Gatorade,beverage
11,greygoose,Grey Goose,greygoose,greygoose,greygoose,Grey Goose,beverage
12,honesttea,Honest Tea,honesttea,honesttea,honesttea,Honest Tea,beverage
13,jackdaniels,Jack Daniel's,jackdaniels_us,jackdaniels,jackdaniels_us,Jack Daniel's,beverage
14,korbel,Korbel,korbel_1882,korbel,korbel_1882,Korbel,beverage
15,lipton,Lipton,lipton,lipton,lipton,Lipton,beverage
16,moetchandon,Moet & Chandon,moetchandon,moetchandon,moetchandon,Moet & Chandon,beverage
17,monsterenergy,Monster,monsterenergy,monsterenergy,monsterenergy,Monster,beverage
18,nesquik,NesQuik,nesquikusa,nesquik,nesquikusa,NesQuik,beverage
19,sanpellegrino,San Pellegrino,sanpellegrino_official,sanpellegrino,sanpellegrino_official,San Pellegrino,beverage
20,snapple,Snapple,snapple,snapple,snapple,Snapple,beverage
21,tazo,Tazo,tazo,tazo,tazo,Tazo,beverage
22,vitaminwater,Vitaminwater,vitaminwater,vitaminwater,vitaminwater,Vitaminwater,beverage
23,welchs,Welch's,welchs,welchs,welchs,Welch's,beverage
24,minutemaid,Minute Maid,None,minutemaid,None,Minute Maid,beverage
25,motts,Mott's,None,motts,None,Mott's,beverage
26,swissmiss,Swiss Miss,None,swissmiss,None,Swiss Miss,beverage
27,None,None,None,abercrombie,abercrombie,Abercrombie & Fitch,apparel
28,None,None,None,adidas,adidas,Adidas,apparel
29,None,None,None,anntaylor,anntaylor,Ann Taylor,apparel
30,None,None,None,bananarepublic,bananarepublic,Banana Republic,apparel
31,None,None,None,carhartt,carhartt,Carhartt,apparel
32,None,None,None,converse,converse,Converse,apparel
33,None,None,None,dockers,dockerskhakis,Dockers,apparel
34,None,None,None,dolcegabbana,dolcegabbana,Dolce & Gabbana,apparel
35,None,None,None,eddiebauer,eddiebauer,Eddie Bauer,apparel
36,None,None,None,gap,gap,Gap,apparel
37,None,None,None,gucci,gucci,Gucci,apparel
38,None,None,None,guess,guess,Guess,apparel
39,None,None,None,hanes,hanesbrasil,Hanes,apparel
40,None,None,None,hollister,hollisterco,Hollister,apparel
41,None,None,None,jcrew,jcrew,J. Crew,apparel
42,None,None,None,joeboxer,joeboxerlicky,Joe Boxer,apparel
43,None,None,None,juicycouture,juicycouture,Juicy Couture,apparel
44,None,None,None,kennethcole,kennethcole,Kenneth Cole,apparel
45,None,None,None,levis,levis,Levi's,apparel
46,None,None,None,llbean,llbean,L.L. Bean,apparel
47,None,None,None,luckybrand,luckybrandme,Lucky Brand Jeans,apparel
48,None,None,None,oldnavy,oldnavy,Old Navy,apparel
49,None,None,None,oshkosh,oshkoshkids,OshKosh,apparel
50,None,None,None,prada,prada,Prada,apparel
51,None,None,None,ralphlauren,ralphlauren,Ralph Lauren,apparel
52,None,None,None,tommyhilfiger,tommyhilfiger,Tommy Hilfiger,apparel
53,None,None,None,underarmour,underarmour,Under Armour,apparel
54,None,None,None,urbanoutfitters,urbanoutfitters,Urban Outfitters,apparel
55,None,None,None,victoriassecret,victoriassecret,Victoria's Secret,apparel

In [47]:
bigdf = pd.merge(data1327, data45678, how='outer')
bigdf

,apparel_brands,official_apparel_brands,apparel_full_brand_names,firm_account,brand_full_name,brand_category,beverage_brands,beverage_full_brand_names,official_beverage_brands,instagram_hashtag
0,bananarepublic,bananarepublic,Banana Republic,bananarepublic,Banana Republic,apparel,None,None,None,bananarepublic
1,juicycouture,juicycouture,Juicy Couture,juicycouture,Juicy Couture,apparel,None,None,None,juicycouture
2,underarmour,underarmour,Under Armour,underarmour,Under Armour,apparel,None,None,None,underarmour
3,levis,levis,Levi's,levis,Levi's,apparel,None,None,None,levis
4,eddiebauer,eddiebauer,Eddie Bauer,eddiebauer,Eddie Bauer,apparel,None,None,None,eddiebauer
5,oldnavy,oldnavy,Old Navy,oldnavy,Old Navy,apparel,None,None,None,oldnavy
6,anntaylor,anntaylor,Ann Taylor,anntaylor,Ann Taylor,apparel,None,None,None,anntaylor
7,converse,converse,Converse,converse,Converse,apparel,None,None,None,converse
8,dolcegabbana,dolcegabbana,Dolce & Gabbana,dolcegabbana,Dolce & Gabbana,apparel,None,None,None,dolcegabbana
9,prada,prada,Prada,prada,Prada,apparel,None,None,None,prada
10,abercrombie,abercrombie,Abercrombie & Fitch,abercrombie,Abercrombie & Fitch,apparel,None,None,None,abercrombie
11,gap,gap,Gap,gap,Gap,apparel,None,None,None,gap
12,adidas,adidas,Adidas,adidas,Adidas,apparel,None,None,None,adidas
13,victoriassecret,victoriassecret,Victoria's Secret,victoriassecret,Victoria's Secret,apparel,None,None,None,victoriassecret
14,carhartt,carhartt,Carhartt,carhartt,Carhartt,apparel,None,None,None,carhartt
15,luckybrand,luckybrandme,Lucky Brand Jeans,luckybrandme,Lucky Brand Jeans,apparel,None,None,None,luckybrand
16,dockers,dockerskhakis,Dockers,dockerskhakis,Dockers,apparel,None,None,None,dockers
17,kennethcole,kennethcole,Kenneth Cole,kennethcole,Kenneth Cole,apparel,None,None,None,kennethcole
18,guess,guess,Guess,guess,Guess,apparel,None,None,None,guess
19,hanes,hanesbrasil,Hanes,hanesbrasil,Hanes,apparel,None,None,None,hanes
20,joeboxer,joeboxerlicky,Joe Boxer,joeboxerlicky,Joe Boxer,apparel,None,None,None,joeboxer
21,urbanoutfitters,urbanoutfitters,Urban Outfitters,urbanoutfitters,Urban Outfitters,apparel,None,None,None,urbanoutfitters
22,llbean,llbean,L.L. Bean,llbean,L.L. Bean,apparel,None,None,None,llbean
23,oshkosh,oshkoshkids,OshKosh,oshkoshkids,OshKosh,apparel,None,None,None,oshkosh
24,ralphlauren,ralphlauren,Ralph Lauren,ralphlauren,Ralph Lauren,apparel,None,None,None,ralphlauren
25,gucci,gucci,Gucci,gucci,Gucci,apparel,None,None,None,gucci
26,tommyhilfiger,tommyhilfiger,Tommy Hilfiger,tommyhilfiger,Tommy Hilfiger,apparel,None,None,None,tommyhilfiger
27,hollister,hollisterco,Hollister,hollisterco,Hollister,apparel,None,None,None,hollister
28,jcrew,jcrew,J. Crew,jcrew,J. Crew,apparel,None,None,None,jcrew
29,None,None,None,bacardiusa,Bacardi,beverage,bacardi,Bacardi,bacardiusa,bacardi
30,None,None,None,bigelowtea,Bigelow's Tea,beverage,bigelow,Bigelow's Tea,bigelowtea,bigelow
31,None,None,None,budlight,Bud Light,beverage,budlight,Bud Light,budlight,budlight
32,None,None,None,budweiser,Budweiser,beverage,budweiser,Budweiser,budweiser,budweiser
33,None,None,None,cocacola,Coca-Cola,beverage,cocacola,Coca-Cola,cocacola,cocacola
34,None,None,None,coorslight,Coors Light,beverage,coorslight,Coors Light,coorslight,coorslight
35,None,None,None,corona,Corona,beverage,corona,Corona,corona,corona
36,None,None,None,domperignon,Dom Perignon,beverage,domperignon,Dom Perignon,domperignon,domperignon
37,None,None,None,drpepper,Dr Pepper,beverage,drpepper,Dr Pepper,drpepper,drpepper
38,None,None,None,fanta,Fanta,beverage,fanta,Fanta,fanta,fanta
39,None,None,None,gatorade,Gatorade,beverage,gatorade,Gatorade,gatorade,gatorade
40,None,None,None,greygoose,Grey Goose,beverage,greygoose,Grey Goose,greygoose,greygoose
41,None,None,None,honesttea,Honest Tea,beverage,honesttea,Honest Tea,honesttea,honesttea
42,None,None,None,jackdaniels_us,Jack Daniel's,beverage,jackdaniels,Jack Daniel's,jackdaniels_us,jackdaniels
43,None,None,None,korbel_1882,Korbel,beverage,korbel,Korbel,korbel_1882,korbel
44,None,None,None,lipton,Lipton,beverage,lipton,Lipton,lipton,lipton
45,None,None,None,moetchandon,Moet & Chandon,beverage,moetchandon,Moet & Chandon,moetchandon,moetchandon
46,None,None,None,monsterenergy,Monster,beverage,monsterenergy,Monster,monsterenergy,monsterenergy
47,None,None,None,nesquikusa,NesQuik,beverage,nesquik,NesQuik,nesquikusa,nesquik
48,None,None,None,sanpellegrino_official,San Pellegrino,beverage,sanpellegrino,San Pellegrino,sanpellegrino_official,sanpellegrino
49,None,None,None,snapple,Snapple,beverage,snapple,Snapple,snapple,snapple
50,None,None,None,tazo,Tazo,beverage,tazo,Tazo,tazo,tazo
51,None,None,None,vitaminwater,Vitaminwater,beverage,vitaminwater,Vitaminwater,vitaminwater,vitaminwater
52,None,None,None,welchs,Welch's,beverage,welchs,Welch's,welchs,welchs
53,NaN,NaN,NaN,None,Minute Maid,beverage,minutemaid,Minute Maid,None,minutemaid
54,NaN,NaN,NaN,None,Mott's,beverage,motts,Mott's,None,motts
55,NaN,NaN,NaN,None,Swiss Miss,beverage,swissmiss,Swiss Miss,None,swissmiss

In [71]:
bigdf = pd.merge(data1327, data4567, how='outer')
bigdf = pd.merge(bigdf, data78, how='outer')
bigdf

,apparel_brands,official_apparel_brands,apparel_full_brand_names,firm_account,brand_full_name,brand_category,beverage_brands,beverage_full_brand_names,official_beverage_brands,instagram_hashtag
0,bananarepublic,bananarepublic,Banana Republic,bananarepublic,Banana Republic,apparel,None,None,None,bananarepublic
1,juicycouture,juicycouture,Juicy Couture,juicycouture,Juicy Couture,apparel,None,None,None,juicycouture
2,underarmour,underarmour,Under Armour,underarmour,Under Armour,apparel,None,None,None,underarmour
3,levis,levis,Levi's,levis,Levi's,apparel,None,None,None,levis
4,eddiebauer,eddiebauer,Eddie Bauer,eddiebauer,Eddie Bauer,apparel,None,None,None,eddiebauer
5,oldnavy,oldnavy,Old Navy,oldnavy,Old Navy,apparel,None,None,None,oldnavy
6,anntaylor,anntaylor,Ann Taylor,anntaylor,Ann Taylor,apparel,None,None,None,anntaylor
7,converse,converse,Converse,converse,Converse,apparel,None,None,None,converse
8,dolcegabbana,dolcegabbana,Dolce & Gabbana,dolcegabbana,Dolce & Gabbana,apparel,None,None,None,dolcegabbana
9,prada,prada,Prada,prada,Prada,apparel,None,None,None,prada
10,abercrombie,abercrombie,Abercrombie & Fitch,abercrombie,Abercrombie & Fitch,apparel,None,None,None,abercrombie
11,gap,gap,Gap,gap,Gap,apparel,None,None,None,gap
12,adidas,adidas,Adidas,adidas,Adidas,apparel,None,None,None,adidas
13,victoriassecret,victoriassecret,Victoria's Secret,victoriassecret,Victoria's Secret,apparel,None,None,None,victoriassecret
14,carhartt,carhartt,Carhartt,carhartt,Carhartt,apparel,None,None,None,carhartt
15,luckybrand,luckybrandme,Lucky Brand Jeans,luckybrandme,Lucky Brand Jeans,apparel,None,None,None,luckybrand
16,dockers,dockerskhakis,Dockers,dockerskhakis,Dockers,apparel,None,None,None,dockers
17,kennethcole,kennethcole,Kenneth Cole,kennethcole,Kenneth Cole,apparel,None,None,None,kennethcole
18,guess,guess,Guess,guess,Guess,apparel,None,None,None,guess
19,hanes,hanesbrasil,Hanes,hanesbrasil,Hanes,apparel,None,None,None,hanes
20,joeboxer,joeboxerlicky,Joe Boxer,joeboxerlicky,Joe Boxer,apparel,None,None,None,joeboxer
21,urbanoutfitters,urbanoutfitters,Urban Outfitters,urbanoutfitters,Urban Outfitters,apparel,None,None,None,urbanoutfitters
22,llbean,llbean,L.L. Bean,llbean,L.L. Bean,apparel,None,None,None,llbean
23,oshkosh,oshkoshkids,OshKosh,oshkoshkids,OshKosh,apparel,None,None,None,oshkosh
24,ralphlauren,ralphlauren,Ralph Lauren,ralphlauren,Ralph Lauren,apparel,None,None,None,ralphlauren
25,gucci,gucci,Gucci,gucci,Gucci,apparel,None,None,None,gucci
26,tommyhilfiger,tommyhilfiger,Tommy Hilfiger,tommyhilfiger,Tommy Hilfiger,apparel,None,None,None,tommyhilfiger
27,hollister,hollisterco,Hollister,hollisterco,Hollister,apparel,None,None,None,hollister
28,jcrew,jcrew,J. Crew,jcrew,J. Crew,apparel,None,None,None,jcrew
29,None,None,None,bacardiusa,Bacardi,beverage,bacardi,Bacardi,bacardiusa,bacardi
30,None,None,None,bigelowtea,Bigelow's Tea,beverage,bigelow,Bigelow's Tea,bigelowtea,bigelow
31,None,None,None,budlight,Bud Light,beverage,budlight,Bud Light,budlight,budlight
32,None,None,None,budweiser,Budweiser,beverage,budweiser,Budweiser,budweiser,budweiser
33,None,None,None,cocacola,Coca-Cola,beverage,cocacola,Coca-Cola,cocacola,cocacola
34,None,None,None,coorslight,Coors Light,beverage,coorslight,Coors Light,coorslight,coorslight
35,None,None,None,corona,Corona,beverage,corona,Corona,corona,corona
36,None,None,None,domperignon,Dom Perignon,beverage,domperignon,Dom Perignon,domperignon,domperignon
37,None,None,None,drpepper,Dr Pepper,beverage,drpepper,Dr Pepper,drpepper,drpepper
38,None,None,None,fanta,Fanta,beverage,fanta,Fanta,fanta,fanta
39,None,None,None,gatorade,Gatorade,beverage,gatorade,Gatorade,gatorade,gatorade
40,None,None,None,greygoose,Grey Goose,beverage,greygoose,Grey Goose,greygoose,greygoose
41,None,None,None,honesttea,Honest Tea,beverage,honesttea,Honest Tea,honesttea,honesttea
42,None,None,None,jackdaniels_us,Jack Daniel's,beverage,jackdaniels,Jack Daniel's,jackdaniels_us,jackdaniels
43,None,None,None,korbel_1882,Korbel,beverage,korbel,Korbel,korbel_1882,korbel
44,None,None,None,lipton,Lipton,beverage,lipton,Lipton,lipton,lipton
45,None,None,None,moetchandon,Moet & Chandon,beverage,moetchandon,Moet & Chandon,moetchandon,moetchandon
46,None,None,None,monsterenergy,Monster,beverage,monsterenergy,Monster,monsterenergy,monsterenergy
47,None,None,None,nesquikusa,NesQuik,beverage,nesquik,NesQuik,nesquikusa,nesquik
48,None,None,None,sanpellegrino_official,San Pellegrino,beverage,sanpellegrino,San Pellegrino,sanpellegrino_official,sanpellegrino
49,None,None,None,snapple,Snapple,beverage,snapple,Snapple,snapple,snapple
50,None,None,None,tazo,Tazo,beverage,tazo,Tazo,tazo,tazo
51,None,None,None,vitaminwater,Vitaminwater,beverage,vitaminwater,Vitaminwater,vitaminwater,vitaminwater
52,None,None,None,welchs,Welch's,beverage,welchs,Welch's,welchs,welchs
53,NaN,NaN,NaN,None,None,beverage,minutemaid,Minute Maid,None,NaN
54,NaN,NaN,NaN,None,None,beverage,motts,Mott's,None,NaN
55,NaN,NaN,NaN,None,None,beverage,swissmiss,Swiss Miss,None,NaN
56,NaN,NaN,NaN,NaN,Minute Maid,NaN,NaN,NaN,NaN,minutemaid
57,NaN,NaN,NaN,NaN,Mott`s,NaN,NaN,NaN,NaN,motts
58,NaN,NaN,NaN,NaN,Swiss Miss,NaN,NaN,NaN,NaN,swissmiss

In [51]:
directory= r"C:\Users\Anonym\Documents\GitHub\DLfM_BrandManagement\data"

os.chdir(directory)
bigdf.tocsv('bigdf.csv')

AttributeError: 'DataFrame' object has no attribute 'tocsv'

### 3. Save Dataframes to csv

Specify directory to put in all data about dataframes for furhter processing.

In [14]:
# to specify
directory= r"C:\Users\Anonym\Documents\GitHub\DLfM_BrandManagement\data"
folder = 'instagram_urls'

os.chdir(directory)
path = os.path.join(directory, folder)
    
try:  
    os.mkdir(folder)
except: 
    pass

os.chdir(path)

#### Save dataframe

In [17]:
data78.to_csv('hashToOfficialName.csv', index=False)

Put all firm account names (of all brand categories) into a list, which can be iterated over to get images from these firm accounts on Instagram. It is used to specify user-profiles Instagram pages.

In [ ]:
firm_usernames = data7.firm_account.values.tolist()

In [ ]:
def write_list_to_file(guest_list, filename):
    """Write the list to csv file."""

    with open(filename, "w") as outfile:
        for entries in guest_list:
            outfile.write(entries)
            outfile.write("\n")

write_list_to_file(firm_usernames, 'firm_usernames.csv')

Put all hashtag names (of all brand categories) into a list, which can be iterated over to get images from these hashtag results on Instagram. It is used to specify hashed Instagram pages.

In [ ]:
instagram_hashtags = data8.instagram_hashtag.values.tolist()

In [ ]:
def write_list_to_file(guest_list, filename):
    """Write the list to csv file."""

    with open(filename, "w") as outfile:
        for entries in guest_list:
            outfile.write(entries)
            outfile.write("\n")

write_list_to_file(instagram_hashtags, 'instagram_hashtags.csv')